name: Run Queries

on:
  workflow_dispatch:

jobs:
  create-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '347.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Create BQ dataset
        run: |
          bq --location=US mk \
          --dataset \
          --default_table_expiration 604800 \
          --description "@saddlefinance/saddle-retroactive-query output for commit ${{ github.sha }}" \
          ${{ secrets.GCP_PROJECT_ID }}:retroactive_${{ github.sha }}

  run-queries:
    needs: create-dataset
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        schema:
          - file: "./src/010_saddle_retroactive_swap.sql"
          - file: "./src/020_saddle_retroactive_lp.sql"

    steps:
      - uses: actions/checkout@v2

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '347.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Run BQ
        run: |
          cat ${{ matrix.schema.file }} | \
          bq --location=US --dataset_id=${{ secrets.GCP_PROJECT_ID }}:retroactive_${{ github.sha }} query \
          --nouse_legacy_sql

